from ubuntu:latest
# copied from linux .github/workflows
RUN dpkg --add-architecture i386 && apt-get update && apt-get install git gcc g++ gcc-multilib g++-multilib make libsdl2-dev zlib1g-dev libsdl2-dev:i386 zlib1g-dev:i386 -y
workdir /pd
